/**
 * Tests for bug-index-gen.js — renders docs/bugs/INDEX.md from per-bug
 * checkpoint.md files.
 */

import { test, describe } from 'node:test';
import assert from 'node:assert/strict';
import { mkdirSync, writeFileSync, existsSync, readFileSync, mkdtempSync, rmSync, readdirSync, utimesSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';

import { regenerateBugIndex } from '../lib/bug-index-gen.js';

function makeTmp() {
  return mkdtempSync(join(tmpdir(), 'bug-index-gen-'));
}

function writeCheckpoint(cwd, code, isoTime) {
  const dir = join(cwd, 'docs', 'bugs', code);
  mkdirSync(dir, { recursive: true });
  const path = join(dir, 'checkpoint.md');
  writeFileSync(path, `# Checkpoint for ${code}\n\n**Time:** ${isoTime}\n\nStuff here.\n`);
  return path;
}

describe('regenerateBugIndex', () => {
  test('no-op when docs/bugs/ does not exist', () => {
    const cwd = makeTmp();
    try {
      regenerateBugIndex(cwd); // should not throw
      assert.equal(existsSync(join(cwd, 'docs', 'bugs', 'INDEX.md')), false);
    } finally {
      rmSync(cwd, { recursive: true, force: true });
    }
  });

  test('empty docs/bugs/ → no INDEX.md written, no error', () => {
    const cwd = makeTmp();
    try {
      mkdirSync(join(cwd, 'docs', 'bugs'), { recursive: true });
      regenerateBugIndex(cwd);
      // Empty directory: no rows to render. We still write a header-only INDEX.md
      // so callers can find it; but the table should be empty. Either behavior
      // (no file OR header-only) is acceptable per the plan; we assert that
      // if it exists, it has the header.
      const indexPath = join(cwd, 'docs', 'bugs', 'INDEX.md');
      if (existsSync(indexPath)) {
        const content = readFileSync(indexPath, 'utf-8');
        assert.match(content, /# Bugs Index/);
      }
    } finally {
      rmSync(cwd, { recursive: true, force: true });
    }
  });

  test('single bug with checkpoint → one row with correct fields', () => {
    const cwd = makeTmp();
    try {
      writeCheckpoint(cwd, 'BUG-001', '2026-04-30T12:00:00.000Z');
      regenerateBugIndex(cwd);
      const indexPath = join(cwd, 'docs', 'bugs', 'INDEX.md');
      assert.ok(existsSync(indexPath), 'INDEX.md should exist');
      const content = readFileSync(indexPath, 'utf-8');
      assert.match(content, /# Bugs Index/);
      assert.match(content, /Generated by compose\. Do not edit by hand\./);
      assert.match(content, /\| Bug \| Last attempt \| Open since \| Status \|/);
      assert.match(content, /BUG-001/);
      assert.match(content, /2026-04-30T12:00:00\.000Z/);
      assert.match(content, /OPEN/);
    } finally {
      rmSync(cwd, { recursive: true, force: true });
    }
  });

  test('multiple bugs → rows sorted by Last attempt desc', () => {
    const cwd = makeTmp();
    try {
      writeCheckpoint(cwd, 'BUG-OLD', '2026-01-01T00:00:00.000Z');
      writeCheckpoint(cwd, 'BUG-MID', '2026-03-15T00:00:00.000Z');
      writeCheckpoint(cwd, 'BUG-NEW', '2026-04-30T12:00:00.000Z');
      regenerateBugIndex(cwd);
      const content = readFileSync(join(cwd, 'docs', 'bugs', 'INDEX.md'), 'utf-8');
      const idxNew = content.indexOf('BUG-NEW');
      const idxMid = content.indexOf('BUG-MID');
      const idxOld = content.indexOf('BUG-OLD');
      assert.ok(idxNew > 0 && idxMid > 0 && idxOld > 0, 'all bugs present');
      assert.ok(idxNew < idxMid, 'newest before mid');
      assert.ok(idxMid < idxOld, 'mid before oldest');
    } finally {
      rmSync(cwd, { recursive: true, force: true });
    }
  });

  test('bug folder without checkpoint.md → row with (no attempts yet) status OPEN', () => {
    const cwd = makeTmp();
    try {
      const dir = join(cwd, 'docs', 'bugs', 'BUG-NOATTEMPT');
      mkdirSync(dir, { recursive: true });
      writeFileSync(join(dir, 'description.md'), '# describe\n');
      regenerateBugIndex(cwd);
      const content = readFileSync(join(cwd, 'docs', 'bugs', 'INDEX.md'), 'utf-8');
      assert.match(content, /BUG-NOATTEMPT/);
      assert.match(content, /\(no attempts yet\)/);
      assert.match(content, /OPEN/);
    } finally {
      rmSync(cwd, { recursive: true, force: true });
    }
  });

  test('bug with closed.md → status CLOSED', () => {
    const cwd = makeTmp();
    try {
      writeCheckpoint(cwd, 'BUG-CLOSED', '2026-04-30T12:00:00.000Z');
      writeFileSync(join(cwd, 'docs', 'bugs', 'BUG-CLOSED', 'closed.md'), '# Closed\n');
      regenerateBugIndex(cwd);
      const content = readFileSync(join(cwd, 'docs', 'bugs', 'INDEX.md'), 'utf-8');
      assert.match(content, /BUG-CLOSED/);
      // The row containing BUG-CLOSED should have CLOSED status
      const row = content.split('\n').find(l => l.includes('BUG-CLOSED'));
      assert.ok(row, 'row found');
      assert.match(row, /CLOSED/);
    } finally {
      rmSync(cwd, { recursive: true, force: true });
    }
  });

  test('atomic write: no leftover INDEX.md.tmp after success', () => {
    const cwd = makeTmp();
    try {
      writeCheckpoint(cwd, 'BUG-ATOM', '2026-04-30T12:00:00.000Z');
      regenerateBugIndex(cwd);
      regenerateBugIndex(cwd); // run twice, simulating concurrent re-render
      const entries = readdirSync(join(cwd, 'docs', 'bugs'));
      assert.ok(entries.includes('INDEX.md'));
      assert.ok(!entries.includes('INDEX.md.tmp'), 'tmp file should not linger');
    } finally {
      rmSync(cwd, { recursive: true, force: true });
    }
  });

  test('atomic write: pre-existing INDEX.md.tmp does not block rename', () => {
    const cwd = makeTmp();
    try {
      writeCheckpoint(cwd, 'BUG-RACE', '2026-04-30T12:00:00.000Z');
      // Simulate stale tmp from a prior crashed invocation
      mkdirSync(join(cwd, 'docs', 'bugs'), { recursive: true });
      writeFileSync(join(cwd, 'docs', 'bugs', 'INDEX.md.tmp'), 'stale\n');
      regenerateBugIndex(cwd);
      const indexPath = join(cwd, 'docs', 'bugs', 'INDEX.md');
      assert.ok(existsSync(indexPath));
      const content = readFileSync(indexPath, 'utf-8');
      assert.match(content, /BUG-RACE/);
      assert.notEqual(content.trim(), 'stale');
    } finally {
      rmSync(cwd, { recursive: true, force: true });
    }
  });
});
