/**
 * lineage.test.js — COMP-PROV-LINEAGE: PROV-O artifact lineage.
 *
 * Covers the term-mapped model in lib/lineage.js:
 *   - CANONICAL_CHAIN stays consistent with lib/lifecycle-modes.js (drift guard)
 *   - marker parse / stamp (wasGeneratedBy, wasDerivedFrom)
 *   - canonical + marker-overridden lineage resolution
 *   - the reachability query (findStaleDescendants) — the load-bearing AC
 */

import { test, describe, after } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, rmSync, utimesSync, statSync } from 'node:fs';
import { join, resolve, dirname } from 'node:path';
import { tmpdir } from 'node:os';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

import {
  CANONICAL_CHAIN,
  generatingPhaseOf,
  extractLineageMarkers,
  canonicalLineageOf,
  lineageOf,
  buildDerivationGraph,
  findStaleDescendants,
  stampLineageContent,
  stampFeatureLineage,
} from '../lib/lineage.js';
import { artifactsOf, edgeEvidenceOf, phaseOrderOf } from '../lib/lifecycle-modes.js';

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const COMPOSE_BIN = join(REPO_ROOT, 'bin', 'compose.js');

const temps = [];
after(() => {
  for (const d of temps) rmSync(d, { recursive: true, force: true });
});
function tmpDir() {
  const d = mkdtempSync(join(tmpdir(), 'lineage-'));
  temps.push(d);
  return d;
}

// Deterministic mtimes: base time + offset seconds.
const BASE = new Date('2026-01-01T00:00:00Z');
function writeAt(dir, file, content, offsetSec) {
  const p = join(dir, file);
  writeFileSync(p, content);
  const t = new Date(BASE.getTime() + offsetSec * 1000);
  utimesSync(p, t, t);
  return p;
}

describe('CANONICAL_CHAIN drift guard vs lifecycle-modes', () => {
  test('chain files match artifactsOf("build") exactly and in order', () => {
    assert.deepEqual(
      CANONICAL_CHAIN.map((e) => e.file),
      artifactsOf('build'),
    );
  });

  test('generating phase agrees with edgeEvidence (from-phase produces the file)', () => {
    for (const [edge, file] of Object.entries(edgeEvidenceOf('build'))) {
      const fromPhase = edge.split('->')[0];
      assert.equal(
        generatingPhaseOf(file),
        fromPhase,
        `${file} should be generated by ${fromPhase}`,
      );
    }
  });

  test('generatingPhaseOf returns null for non-canonical files', () => {
    assert.equal(generatingPhaseOf('random.md'), null);
  });

  test('every chain phase exists in phaseOrder and preserves relative order', () => {
    const order = phaseOrderOf('build');
    const chainPhases = CANONICAL_CHAIN.map((e) => e.phase);
    for (const p of chainPhases) {
      assert.ok(order.includes(p), `chain phase ${p} missing from phaseOrder`);
    }
    // Chain must be a subsequence of phaseOrder (no reordering drift).
    const idxs = chainPhases.map((p) => order.indexOf(p));
    for (let i = 1; i < idxs.length; i++) {
      assert.ok(idxs[i] > idxs[i - 1], `chain phase order drifted at ${chainPhases[i]}`);
    }
  });
});

describe('extractLineageMarkers', () => {
  test('parses wasGeneratedBy and single wasDerivedFrom', () => {
    const c = '<!-- wasGeneratedBy: blueprint -->\n<!-- wasDerivedFrom: design.md -->\n# X';
    assert.deepEqual(extractLineageMarkers(c), {
      wasGeneratedBy: 'blueprint',
      wasDerivedFrom: ['design.md'],
    });
  });

  test('parses comma-separated wasDerivedFrom list', () => {
    const c = '<!-- wasDerivedFrom: design.md, prd.md -->\n# X';
    assert.deepEqual(extractLineageMarkers(c).wasDerivedFrom, ['design.md', 'prd.md']);
  });

  test('returns nulls when no markers present', () => {
    assert.deepEqual(extractLineageMarkers('# just a title\n'), {
      wasGeneratedBy: null,
      wasDerivedFrom: null,
    });
  });

  test('coexists with the phase marker', () => {
    const c = '<!-- phase: blueprint -->\n<!-- wasGeneratedBy: blueprint -->\n# X';
    assert.equal(extractLineageMarkers(c).wasGeneratedBy, 'blueprint');
  });

  test('an empty wasDerivedFrom marker is treated as absent (no phantom [])', () => {
    const c = '<!-- wasDerivedFrom:  -->\n# X';
    assert.equal(extractLineageMarkers(c).wasDerivedFrom, null);
  });

  test('does NOT parse a marker embedded in prose or backticks (anchored)', () => {
    const c = 'See the marker `<!-- wasDerivedFrom: typo.md -->` for an example.\n# X';
    assert.equal(extractLineageMarkers(c).wasDerivedFrom, null);
  });
});

describe('canonicalLineageOf', () => {
  test('first artifact derives from nothing', () => {
    const lin = canonicalLineageOf('design.md', ['design.md', 'blueprint.md']);
    assert.deepEqual(lin.wasDerivedFrom, []);
    assert.equal(lin.wasGeneratedBy, 'explore_design');
  });

  test('derives from the immediate existing predecessor', () => {
    const lin = canonicalLineageOf('blueprint.md', ['design.md', 'blueprint.md', 'plan.md']);
    assert.deepEqual(lin.wasDerivedFrom, ['design.md']);
    assert.equal(lin.wasGeneratedBy, 'blueprint');
  });

  test('skips missing predecessors (skippable phases)', () => {
    // prd.md / architecture.md absent → blueprint derives from design.md
    const lin = canonicalLineageOf('plan.md', ['design.md', 'plan.md']);
    assert.deepEqual(lin.wasDerivedFrom, ['design.md']);
  });

  test('non-canonical file → empty lineage', () => {
    const lin = canonicalLineageOf('notes.md', ['notes.md']);
    assert.deepEqual(lin, { entity: 'notes.md', wasGeneratedBy: null, wasDerivedFrom: [] });
  });
});

describe('lineageOf (marker override vs canonical)', () => {
  test('returns null for a missing file', () => {
    const dir = tmpDir();
    assert.equal(lineageOf(dir, 'design.md'), null);
  });

  test('falls back to canonical when no markers', () => {
    const dir = tmpDir();
    writeFileSync(join(dir, 'design.md'), '# Design\n');
    writeFileSync(join(dir, 'blueprint.md'), '# Blueprint\n');
    const lin = lineageOf(dir, 'blueprint.md');
    assert.equal(lin.source, 'canonical');
    assert.deepEqual(lin.wasDerivedFrom, ['design.md']);
    assert.equal(lin.wasGeneratedBy, 'blueprint');
  });

  test('marker overrides canonical derivation', () => {
    const dir = tmpDir();
    writeFileSync(join(dir, 'design.md'), '# Design\n');
    writeFileSync(join(dir, 'prd.md'), '# PRD\n');
    writeFileSync(
      join(dir, 'blueprint.md'),
      '<!-- wasDerivedFrom: prd.md -->\n# Blueprint\n',
    );
    const lin = lineageOf(dir, 'blueprint.md');
    assert.equal(lin.source, 'marker');
    assert.deepEqual(lin.wasDerivedFrom, ['prd.md']);
  });
});

describe('buildDerivationGraph', () => {
  test('maps each existing artifact to its parents', () => {
    const dir = tmpDir();
    writeFileSync(join(dir, 'design.md'), '# D\n');
    writeFileSync(join(dir, 'blueprint.md'), '# B\n');
    writeFileSync(join(dir, 'plan.md'), '# P\n');
    const g = buildDerivationGraph(dir);
    assert.deepEqual(g.get('design.md'), []);
    assert.deepEqual(g.get('blueprint.md'), ['design.md']);
    assert.deepEqual(g.get('plan.md'), ['blueprint.md']);
  });
});

describe('findStaleDescendants — the reachability query', () => {
  test('editing design.md marks blueprint.md and plan.md stale', () => {
    const dir = tmpDir();
    // Descendants written first (older), design.md edited last (newest).
    writeAt(dir, 'blueprint.md', '# Blueprint\n', 10);
    writeAt(dir, 'plan.md', '# Plan\n', 20);
    writeAt(dir, 'design.md', '# Design (edited)\n', 100);

    const stale = findStaleDescendants(dir, 'design.md');
    const staleFiles = stale.filter((r) => r.stale).map((r) => r.file);
    assert.deepEqual(staleFiles.sort(), ['blueprint.md', 'plan.md']);
    assert.ok(stale.every((r) => r.derivedFromChanged));
  });

  test('descendants newer than the change are NOT stale', () => {
    const dir = tmpDir();
    writeAt(dir, 'design.md', '# Design\n', 10);
    writeAt(dir, 'blueprint.md', '# Blueprint\n', 50);
    writeAt(dir, 'plan.md', '# Plan\n', 60);

    const stale = findStaleDescendants(dir, 'design.md');
    assert.equal(stale.filter((r) => r.stale).length, 0);
    // still reports them as descendants
    assert.deepEqual(stale.map((r) => r.file).sort(), ['blueprint.md', 'plan.md']);
  });

  test('transitive: changing design.md reaches plan.md even with blueprint between', () => {
    const dir = tmpDir();
    writeAt(dir, 'blueprint.md', '# B\n', 10);
    writeAt(dir, 'plan.md', '# P\n', 20);
    writeAt(dir, 'design.md', '# D\n', 100);
    const stale = findStaleDescendants(dir, 'design.md');
    assert.ok(stale.some((r) => r.file === 'plan.md' && r.stale));
  });

  test('leaf artifact has no descendants', () => {
    const dir = tmpDir();
    writeAt(dir, 'design.md', '# D\n', 10);
    writeAt(dir, 'plan.md', '# P\n', 20);
    assert.deepEqual(findStaleDescendants(dir, 'plan.md'), []);
  });

  test('marker override redirects the graph (plan derived from design directly)', () => {
    const dir = tmpDir();
    writeAt(dir, 'design.md', '# D\n', 100);
    writeAt(dir, 'blueprint.md', '# B\n', 200); // newer than design
    // plan.md declares it came straight from design.md, skipping blueprint
    writeAt(dir, 'plan.md', '<!-- wasDerivedFrom: design.md -->\n# P\n', 20);

    const stale = findStaleDescendants(dir, 'design.md');
    const byFile = Object.fromEntries(stale.map((r) => [r.file, r.stale]));
    assert.equal(byFile['plan.md'], true, 'plan.md is stale vs design.md');
    // blueprint.md is newer than design.md → descendant but not stale
    assert.equal(byFile['blueprint.md'], false);
  });
});

describe('stampLineageContent', () => {
  test('adds markers at the top when no phase marker', () => {
    const out = stampLineageContent('# Blueprint\n', {
      wasGeneratedBy: 'blueprint',
      wasDerivedFrom: ['design.md'],
    });
    const lines = out.split('\n');
    assert.equal(lines[0], '<!-- wasGeneratedBy: blueprint -->');
    assert.equal(lines[1], '<!-- wasDerivedFrom: design.md -->');
    assert.equal(lines[2], '# Blueprint');
  });

  test('inserts after an existing phase marker, leaving it intact', () => {
    const out = stampLineageContent('<!-- phase: blueprint -->\n# B\n', {
      wasGeneratedBy: 'blueprint',
      wasDerivedFrom: ['design.md'],
    });
    const lines = out.split('\n');
    assert.equal(lines[0], '<!-- phase: blueprint -->');
    assert.equal(lines[1], '<!-- wasGeneratedBy: blueprint -->');
    assert.equal(lines[2], '<!-- wasDerivedFrom: design.md -->');
  });

  test('is idempotent — re-stamping does not duplicate markers', () => {
    const lineage = { wasGeneratedBy: 'blueprint', wasDerivedFrom: ['design.md'] };
    const once = stampLineageContent('# B\n', lineage);
    const twice = stampLineageContent(once, lineage);
    assert.equal(once, twice);
    const count = (twice.match(/wasGeneratedBy/g) || []).length;
    assert.equal(count, 1);
  });

  test('re-stamping replaces stale lineage', () => {
    const first = stampLineageContent('# B\n', {
      wasGeneratedBy: 'blueprint',
      wasDerivedFrom: ['prd.md'],
    });
    const second = stampLineageContent(first, {
      wasGeneratedBy: 'blueprint',
      wasDerivedFrom: ['design.md'],
    });
    assert.ok(second.includes('<!-- wasDerivedFrom: design.md -->'));
    assert.ok(!second.includes('prd.md'));
  });

  test('empty lineage strips existing markers', () => {
    const withMarkers = '<!-- wasGeneratedBy: blueprint -->\n# B\n';
    const out = stampLineageContent(withMarkers, { wasGeneratedBy: null, wasDerivedFrom: [] });
    assert.ok(!out.includes('wasGeneratedBy'));
    assert.ok(out.includes('# B'));
  });
});

describe('stampFeatureLineage (on disk)', () => {
  test('materialises markers on every canonical artifact, idempotently', () => {
    const dir = tmpDir();
    writeFileSync(join(dir, 'design.md'), '# Design\n');
    writeFileSync(join(dir, 'blueprint.md'), '# Blueprint\n');

    const first = stampFeatureLineage(dir);
    assert.deepEqual(first.map((r) => r.file), ['design.md', 'blueprint.md']);
    assert.ok(first.every((r) => r.changed));
    assert.ok(readFileSync(join(dir, 'blueprint.md'), 'utf-8').includes('<!-- wasDerivedFrom: design.md -->'));

    const second = stampFeatureLineage(dir);
    assert.ok(second.every((r) => !r.changed), 're-stamp is a no-op');
  });

  test('preserves artifact mtime — stamping does not erase existing staleness', () => {
    const dir = tmpDir();
    // blueprint written before design was edited → already stale.
    writeAt(dir, 'blueprint.md', '# Blueprint\n', 10);
    writeAt(dir, 'design.md', '# Design (edited)\n', 100);
    const beforeBp = statSync(join(dir, 'blueprint.md')).mtimeMs;

    stampFeatureLineage(dir);

    // mtimes preserved, so the pre-existing staleness is still visible.
    assert.equal(statSync(join(dir, 'blueprint.md')).mtimeMs, beforeBp);
    const stale = findStaleDescendants(dir, 'design.md');
    assert.ok(stale.some((r) => r.file === 'blueprint.md' && r.stale),
      'blueprint.md should still be stale after a retrofit stamp');
  });

  test('idempotent for an origin artifact carrying only wasGeneratedBy', () => {
    const dir = tmpDir();
    // design.md is chain origin: canonical wasDerivedFrom is empty.
    writeFileSync(join(dir, 'design.md'), '# Design\n');
    const first = stampFeatureLineage(dir);
    assert.ok(first[0].changed);
    const second = stampFeatureLineage(dir);
    assert.ok(second.every((r) => !r.changed), 'origin artifact re-stamp is a no-op');
  });

  test('preserves a hand-authored marker override', () => {
    const dir = tmpDir();
    writeFileSync(join(dir, 'design.md'), '# Design\n');
    writeFileSync(join(dir, 'prd.md'), '# PRD\n');
    writeFileSync(join(dir, 'blueprint.md'), '<!-- wasDerivedFrom: prd.md -->\n# Blueprint\n');
    stampFeatureLineage(dir);
    const bp = readFileSync(join(dir, 'blueprint.md'), 'utf-8');
    assert.ok(bp.includes('<!-- wasDerivedFrom: prd.md -->'));
    assert.ok(!bp.includes('design.md'), 'override not overwritten with canonical predecessor');
  });
});

describe('compose lineage CLI', () => {
  function project() {
    const root = tmpDir();
    const fdir = join(root, 'docs', 'features', 'DEMO-1');
    mkdirSync(fdir, { recursive: true });
    return { root, fdir };
  }
  function run(root, argv) {
    return execFileSync('node', [COMPOSE_BIN, ...argv], { cwd: root, encoding: 'utf-8' });
  }

  test('stamp then stale reports downstream staleness', () => {
    const { root, fdir } = project();
    writeFileSync(join(fdir, 'blueprint.md'), '# B\n');
    writeFileSync(join(fdir, 'plan.md'), '# P\n');
    writeFileSync(join(fdir, 'design.md'), '# D\n');

    const stampOut = run(root, ['lineage', 'stamp', '--feature', 'DEMO-1']);
    assert.match(stampOut, /wasGeneratedBy=blueprint/);

    // Simulate editing design.md after the fact — make it the newest file.
    const old = new Date(BASE.getTime() + 10_000);
    utimesSync(join(fdir, 'blueprint.md'), old, old);
    utimesSync(join(fdir, 'plan.md'), old, old);
    const now = new Date(BASE.getTime() + 100_000);
    utimesSync(join(fdir, 'design.md'), now, now);

    const staleOut = run(root, ['lineage', 'stale', '--feature', 'DEMO-1', '--changed', 'design.md']);
    assert.match(staleOut, /blueprint\.md/);
    assert.match(staleOut, /plan\.md/);
    assert.match(staleOut, /STALE/);
  });

  test('rejects a --feature that is not a valid feature code (path traversal)', () => {
    const { root } = project();
    let err;
    try {
      run(root, ['lineage', 'show', '--feature', 'DEMO-1/../DEMO-1']);
    } catch (e) {
      err = e;
    }
    assert.ok(err, 'should exit non-zero');
    assert.match(String(err.stderr || ''), /Invalid feature code/);
  });

  test('rejects a --changed with path separators (traversal)', () => {
    const { root, fdir } = project();
    writeFileSync(join(fdir, 'design.md'), '# D\n');
    let err;
    try {
      run(root, ['lineage', 'stale', '--feature', 'DEMO-1', '--changed', '../../etc/hosts']);
    } catch (e) {
      err = e;
    }
    assert.ok(err, 'should exit non-zero');
    assert.match(String(err.stderr || ''), /bare filename/);
  });

  test('show emits JSON derivation graph', () => {
    const { root, fdir } = project();
    writeFileSync(join(fdir, 'design.md'), '# D\n');
    writeFileSync(join(fdir, 'plan.md'), '# P\n');
    const out = run(root, ['lineage', 'show', '--feature', 'DEMO-1', '--format', 'json']);
    const graph = JSON.parse(out);
    assert.deepEqual(graph['design.md'], []);
    assert.deepEqual(graph['plan.md'], ['design.md']); // blueprint skipped
  });
});

describe('no RDF runtime dependency', () => {
  test('lib/lineage.js imports only node builtins + lifecycle-modes', () => {
    const src = readFileSync(new URL('../lib/lineage.js', import.meta.url), 'utf-8');
    const imports = [...src.matchAll(/from\s+'([^']+)'/g)].map((m) => m[1]);
    for (const imp of imports) {
      const ok = imp.startsWith('node:') || imp === './lifecycle-modes.js';
      assert.ok(ok, `unexpected import: ${imp}`);
    }
  });
});
