/**
 * proof-run.test.js — Integration test for the full build.stratum.yaml spec.
 *
 * Validates the 12-step lifecycle pipeline with mock connectors and
 * auto-approved gates. Proves the dispatch loop handles skips, gates,
 * sub-flows, artifact file_exists ensures, and cross-agent recovery.
 *
 * Requires the adjacent live TS Stratum MCP bin.
 */

import { test, before, after, describe, beforeEach, afterEach } from 'node:test';
import assert from 'node:assert/strict';
import {
  mkdtempSync, mkdirSync, writeFileSync, readFileSync,
  existsSync, rmSync,
} from 'node:fs';
import { join, resolve, dirname } from 'node:path';
import { tmpdir } from 'node:os';
import { execFileSync } from 'node:child_process';
import { PassThrough } from 'node:stream';

import { runBuild as runBuildRuntime } from '../lib/build.js';
import { runBuildWithAgentFactory } from './helpers/ts-agent-harness.js';

const runBuild = (featureCode, options) => runBuildWithAgentFactory(runBuildRuntime, featureCode, options);

const ROOT = resolve(dirname(import.meta.url.replace('file://', '')));

// ---------------------------------------------------------------------------
// Live TS fixture
// ---------------------------------------------------------------------------

import { TS_MCP_BIN } from './helpers/stratum-test-bin.js';
const stratumAvailable = existsSync(TS_MCP_BIN);
const stratumStateRoot = mkdtempSync(join(tmpdir(), 'proof-run-stratum-state-'));
const previousStateRoot = process.env.STRATUM_STATE_ROOT;
const previousNodeEnv = process.env.NODE_ENV;

before(() => {
  process.env.STRATUM_STATE_ROOT = stratumStateRoot;
  process.env.NODE_ENV = 'test';
});
after(() => {
  if (previousStateRoot === undefined) delete process.env.STRATUM_STATE_ROOT;
  else process.env.STRATUM_STATE_ROOT = previousStateRoot;
  if (previousNodeEnv === undefined) delete process.env.NODE_ENV;
  else process.env.NODE_ENV = previousNodeEnv;
  rmSync(stratumStateRoot, { recursive: true, force: true });
});

// ---------------------------------------------------------------------------
// Mock connector
// ---------------------------------------------------------------------------

/**
 * Creates a connector factory that returns canned results per step.
 * Tracks which steps were dispatched and with which agent type.
 * Creates artifact files that stratum's file_exists ensures check for.
 *
 * @param {Array}  dispatches  - Collects { stepId, agentType, promptSnippet }
 * @param {string} featureDir  - Path to the feature folder for artifact creation
 * @param {object} [overrides] - Per-step result overrides: { stepId: result }
 */
function mockConnectorFactory(dispatches, featureDir, overrides = {}) {
  // Map step IDs to the artifact files their ensure conditions expect.
  // The result.artifact field must match for file_exists(result.artifact) to pass.
  const artifactMap = {
    explore_design: 'design.md',
    blueprint: 'blueprint.md',
    plan: 'plan.md',
  };

  return function factory(agentType, connectorOpts) {
    return {
      async *run(prompt, _runOpts) {
        // Extract step_id from the prompt (format: step "step_id")
        const stepMatch = prompt.match(/step "([^"]+)"/);
        const stepId = stepMatch?.[1] ?? 'unknown';
        const bareStepId = stepId.split('/').at(-1);

        dispatches.push({ stepId, bareStepId, agentType, promptSnippet: prompt.slice(0, 120) });

        // Create artifact file if this step produces one
        const artifactFile = artifactMap[bareStepId];
        if (artifactFile) {
          mkdirSync(featureDir, { recursive: true });
          writeFileSync(
            join(featureDir, artifactFile),
            `# ${bareStepId}\nGenerated by mock connector.`
          );
        }

        // Consumer worktree dispatches must leave a real retained diff.
        if (stepId.startsWith('execute/')) {
          const worktree = connectorOpts?.cwd;
          mkdirSync(join(worktree, 'src'), { recursive: true });
          writeFileSync(join(worktree, 'src', 'main.js'), 'export const proof = true;\n');
        }

        // Check for per-step overrides
        const overrideValue = overrides[stepId] ?? overrides[bareStepId];
        if (overrideValue) {
          const override = typeof overrideValue === 'function'
            ? overrideValue(dispatches)
            : overrideValue;
          yield { type: 'assistant', content: JSON.stringify(override) };
          yield { type: 'system', subtype: 'complete', agent: 'mock' };
          return;
        }

        // Default contract-matching result
        const result = getStepResult(stepId, featureDir);
        yield { type: 'assistant', content: JSON.stringify(result) };
        yield { type: 'system', subtype: 'complete', agent: 'mock' };
      },
      interrupt() {},
      get isRunning() { return false; },
    };
  };
}

function getStepResult(stepId, featureDir) {
  const bareStepId = stepId.split('/').at(-1);
  const artifactMap = {
    explore_design: 'design.md',
    blueprint: 'blueprint.md',
    plan: 'plan.md',
  };
  const artifactFile = artifactMap[bareStepId];
  // For PhaseResult steps: artifact must be relative path that file_exists can verify
  const artifactPath = artifactFile
    ? `docs/features/${featureDir.split('/').pop()}/${artifactFile}`
    : `${stepId}.md`;

  const phaseResult = {
    phase: bareStepId,
    artifact: artifactPath,
    outcome: 'complete',
    summary: `${bareStepId} completed`,
  };
  const reviewResult = {
    clean: true, summary: 'No issues found', findings: [], meta: {},
    lenses_run: [], auto_fixes: [], asks: [],
  };
  const testResult = { passing: true, summary: 'All tests pass', failures: [] };
  const taskGraph = {
    tasks: [
      {
        id: 'task-1',
        description: 'Implement the main feature logic',
        files_owned: ['src/main.js'],
        files_read: ['src/util.js'],
        depends_on: [],
      },
    ],
  };

  // Triage result for parallel_review sub-flow
  const triageResult = {
    tasks: [
      { id: 'diff-quality', lens_name: 'diff-quality', lens_focus: 'diff quality', confidence_gate: 0.7, exclusions: '' },
      { id: 'contract-compliance', lens_name: 'contract-compliance', lens_focus: 'contract', confidence_gate: 0.7, exclusions: '' },
    ],
  };
  // Lens finding result (clean)
  const lensResult = { ...reviewResult, summary: 'Lens clean' };
  // Merged review result
  const mergedReviewResult = { clean: true, summary: 'No issues found', findings: [], must_fix_count: 0 };

  if (stepId.startsWith('execute/')) {
    return { outcome: 'complete', summary: 'Task implemented', files_changed: ['src/main.js'] };
  }
  if (stepId.startsWith('review_lenses/')) return lensResult;

  switch (bareStepId) {
    case 'decompose': return taskGraph;
    case 'review': return reviewResult;
    case 'triage':
    case 'review_triage': return triageResult;
    case 'review_lenses': return lensResult;
    case 'diff-quality': return lensResult;
    case 'contract-compliance': return lensResult;
    case 'debug-discipline': return lensResult;
    case 'security': return lensResult;
    case 'framework': return lensResult;
    case 'merge':
    case 'merge_review':
    case 'review_merge': return { ...reviewResult, ...mergedReviewResult };
    case 'review_check': return reviewResult;
    case 'run_tests': return testResult;
    case 'coverage_check': return testResult;
    case 'ship': return {
      ...phaseResult,
      plan_items: [{ text: 'test item', file: 'src/main.js', critical: false }],
      files_changed: ['src/main.js'],
    };
    default: return phaseResult;
  }
}

// ---------------------------------------------------------------------------
// Gate auto-approve helper
// ---------------------------------------------------------------------------

function createAutoApproveGateOpts() {
  const output = new PassThrough();
  output.on('data', () => {}); // drain

  return {
    get input() {
      const input = new PassThrough();
      setImmediate(() => {
        input.write('a\n');
        setImmediate(() => { input.write('LGTM\n'); });
      });
      return input;
    },
    output,
  };
}

// ---------------------------------------------------------------------------
// Test setup
// ---------------------------------------------------------------------------

function setupProofProject(tmpDir) {
  const composeDir = join(tmpDir, '.compose');
  mkdirSync(join(composeDir, 'data'), { recursive: true });
  writeFileSync(
    join(composeDir, 'compose.json'),
    JSON.stringify({ version: '1.0', capabilities: { stratum: true } })
  );

  const featureDir = join(tmpDir, 'docs', 'features', 'PROOF-1');
  mkdirSync(featureDir, { recursive: true });
  writeFileSync(join(featureDir, 'design.md'), '# Proof Run\nValidating compose build pipeline.');

  const pipeDir = join(tmpDir, 'pipelines');
  mkdirSync(pipeDir, { recursive: true });
  const realSpec = join(ROOT, '..', 'pipelines', 'build.stratum.yaml');
  // C5 (ruling): proof-run exercises the production build.stratum.yaml UNMODIFIED.
  // Ship's unevaluable `judged` ensure was removed at the source (it failed closed
  // from the judge's {result, input} even on evidenced results — it would have
  // killed real TS-default builds at ship); ship remains gated by ship_gate.
  const fixtureSpec = readFileSync(realSpec, 'utf8');
  writeFileSync(join(pipeDir, 'build.stratum.yaml'), fixtureSpec);

  mkdirSync(join(tmpDir, 'src'), { recursive: true });
  writeFileSync(join(tmpDir, 'src', 'util.js'), 'export const util = true;\n');
  execFileSync('git', ['init', '-q'], { cwd: tmpDir });
  execFileSync('git', ['config', 'user.email', 'proof@example.com'], { cwd: tmpDir });
  execFileSync('git', ['config', 'user.name', 'Proof Test'], { cwd: tmpDir });
  execFileSync('git', ['add', '.'], { cwd: tmpDir });
  execFileSync('git', ['commit', '-qm', 'fixture'], { cwd: tmpDir });

  return { composeDir, featureDir, pipeDir };
}

// ---------------------------------------------------------------------------
// Test: happy path — all steps pass on first try
// ---------------------------------------------------------------------------

describe('proof run: full pipeline', { skip: !stratumAvailable && 'TS stratum MCP bin not found' }, () => {
  let tmpDir;
  let dispatches;
  let featureDir;

  before(() => {
    tmpDir = mkdtempSync(join(tmpdir(), 'proof-run-'));
    const project = setupProofProject(tmpDir);
    featureDir = project.featureDir;
    dispatches = [];
  });

  after(() => {
    rmSync(tmpDir, { recursive: true, force: true });
  });

  test('16-step pipeline completes with mock connectors', { timeout: 120000 }, async () => {
    const gateOpts = createAutoApproveGateOpts();

    await runBuild('PROOF-1', {
      cwd: tmpDir,
      connectorFactory: mockConnectorFactory(dispatches, featureDir),
      description: 'Proof run integration test',
      gateOpts,
    });

    // --- Verify dispatched steps ---
    const stepIds = dispatches.map(d => d.stepId);
    const bareStepIds = dispatches.map(d => d.bareStepId);

    // These steps should execute (not skipped).
    // v0.3: explore_design, blueprint, verification, plan, decompose are agent-dispatched.
    // execute is TS consumer fanout — its tasks are dispatched individually.
    for (const step of ['explore_design', 'blueprint', 'verification', 'plan', 'decompose']) {
      assert.ok(bareStepIds.includes(step), `Step "${step}" should have been dispatched`);
    }

    // Skipped steps should NOT appear in dispatches
    for (const step of ['prd', 'architecture', 'report']) {
      assert.ok(!bareStepIds.includes(step), `Step "${step}" should be skipped, not dispatched`);
    }

    // Sub-flow steps should have dispatched
    assert.ok(stepIds.some((id) => id.endsWith('/review')), 'review sub-flow step should dispatch');
    assert.ok(stepIds.some((id) => id.endsWith('/run_tests')), 'coverage sub-flow step should dispatch');

    // Parallel dispatch tasks should have dispatched (task-1 from mock decompose)
    assert.ok(dispatches.some(d => d.stepId.startsWith('execute/')),
      'TS consumer fanout should dispatch decomposed tasks');

    // --- Verify cross-agent dispatch ---
    const reviewDispatch = dispatches.find(d => d.stepId.endsWith('/review') && d.agentType === 'codex');
    assert.equal(reviewDispatch.agentType, 'codex', 'review step should dispatch to codex agent');

    // Parallel dispatch tasks use the agent from the execute step spec (claude)
    const taskDispatch = dispatches.find(d => d.stepId.startsWith('execute/'));
    assert.equal(taskDispatch.agentType, 'claude', 'parallel dispatch tasks should dispatch to claude agent');

    // --- Verify audit trail ---
    const auditPath = join(tmpDir, 'docs', 'features', 'PROOF-1', 'audit.json');
    assert.ok(existsSync(auditPath), 'audit.json should be written');
    const audit = JSON.parse(readFileSync(auditPath, 'utf-8'));
    assert.equal(audit.status, 'completed', 'audit status should be completed');
    assert.ok(Array.isArray(audit.events), 'audit should have an event trail');
    // C5: restore HEAD's duration assertion — the TS audit exposes elapsed wall
    // time under flowSpent.ms (the v0.3 audit.total_duration_ms's successor).
    assert.equal(typeof audit.flowSpent?.ms, 'number', 'audit should expose flowSpent.ms');
    assert.ok(audit.flowSpent.ms >= 0, 'flowSpent.ms should be non-negative');

    // Trace should include skipped entries
    const skipEntries = audit.events.filter(t => t.type === 'skipped');
    assert.ok(skipEntries.length >= 3,
      `Should have at least 3 skip entries (prd, architecture, report), got ${skipEntries.length}`);

    // Trace should include gate entries
    const gateEntries = audit.events.filter(t => t.type === 'gate_resolved');
    assert.ok(gateEntries.length >= 3,
      `Should have at least 3 gate entries (design, plan, ship), got ${gateEntries.length}`);

    // --- Verify vision state ---
    const visionPath = join(tmpDir, '.compose', 'data', 'vision-state.json');
    assert.ok(existsSync(visionPath), 'vision-state.json should exist');
    const vision = JSON.parse(readFileSync(visionPath, 'utf-8'));
    const item = vision.items.find(i => i.lifecycle?.featureCode === 'PROOF-1');
    assert.ok(item, 'must have feature item');
    assert.equal(item.status, 'complete', 'item status should be complete');

    // Gates should be resolved
    const gates = vision.gates.filter(g => g.itemId === item.id);
    assert.ok(gates.length >= 3, `Should have at least 3 gates, got ${gates.length}`);
    for (const gate of gates) {
      assert.equal(gate.status, 'resolved', `Gate ${gate.id} should be resolved`);
      assert.equal(gate.outcome, 'approve', `Gate ${gate.id} outcome should be 'approve'`);
    }

    // --- Verify terminal state (file retained per STRAT-COMP-4) ---
    const activePath = join(tmpDir, '.compose', 'data', 'active-build.json');
    assert.ok(existsSync(activePath), 'active-build.json should be retained');
    const activeState = JSON.parse(readFileSync(activePath, 'utf-8'));
    assert.equal(activeState.status, 'complete', 'active-build.json should have terminal status "complete"');
    assert.ok(activeState.completedAt, 'active-build.json should have completedAt');
  });
});

// ---------------------------------------------------------------------------
// Test: review failure triggers cross-agent recovery
// ---------------------------------------------------------------------------

describe('proof run: cross-agent recovery', { skip: !stratumAvailable && 'TS stratum MCP bin not found' }, () => {
  let tmpDir;
  let featureDir;

  beforeEach(() => {
    tmpDir = mkdtempSync(join(tmpdir(), 'proof-recovery-'));
    const project = setupProofProject(tmpDir);
    featureDir = project.featureDir;
  });

  afterEach(() => {
    rmSync(tmpDir, { recursive: true, force: true });
  });

  test('failing review triggers claude fix then codex re-review', { timeout: 120000 }, async () => {
    const dispatches = [];

    // Review fails on first call (codex), then passes on second (after claude fix)
    let reviewCallCount = 0;
    const overrides = {
      review: () => {
        reviewCallCount++;
        if (reviewCallCount === 1) {
          return {
            clean: false,
            summary: 'Found issues',
            findings: [
              { severity: 'must-fix', confidence: 10, finding: 'unused import' },
              { severity: 'should-fix', confidence: 10, finding: 'missing test' },
            ],
            meta: {}, lenses_run: [], auto_fixes: [], asks: [],
          };
        }
        return { clean: true, summary: 'All clean', findings: [], meta: {}, lenses_run: [], auto_fixes: [], asks: [] };
      },
    };

    const gateOpts = createAutoApproveGateOpts();

    await runBuild('PROOF-1', {
      cwd: tmpDir,
      connectorFactory: mockConnectorFactory(dispatches, featureDir, overrides),
      description: 'Recovery test',
      gateOpts,
    });

    // Should see: codex review (fail) → claude fix → codex review (pass)
    // Note: the fix prompt also contains step "review", so all three dispatches
    // have stepId === 'review'. Distinguish by agentType.
    const reviewDispatches = dispatches.filter(d => d.stepId.endsWith('/review'));
    assert.ok(reviewDispatches.length >= 3,
      `Should have at least 3 review dispatches (codex fail + claude fix + codex pass), got ${reviewDispatches.length}`);

    // First dispatch should be codex (the failing review)
    assert.equal(reviewDispatches[0].agentType, 'codex', '1st review dispatch should be codex');

    // There should be a claude fix dispatch (cross-agent recovery)
    const claudeFix = reviewDispatches.find(d => d.agentType === 'claude');
    assert.ok(claudeFix, 'Should have a claude fix dispatch (cross-agent recovery)');

    // The claude fix should come after the first codex review
    const firstCodexIdx = dispatches.indexOf(reviewDispatches[0]);
    const claudeFixIdx = dispatches.indexOf(claudeFix);
    assert.ok(claudeFixIdx > firstCodexIdx, 'Claude fix should come after first codex review');

    // There should be a second codex review after the claude fix
    const codexAfterFix = reviewDispatches.find(
      d => d.agentType === 'codex' && dispatches.indexOf(d) > claudeFixIdx
    );
    assert.ok(codexAfterFix, 'Should have a codex re-review after claude fix');

    // Build should complete successfully
    const auditPath = join(tmpDir, 'docs', 'features', 'PROOF-1', 'audit.json');
    assert.ok(existsSync(auditPath), 'audit.json should be written');
    const audit = JSON.parse(readFileSync(auditPath, 'utf-8'));
    assert.equal(audit.status, 'completed', 'build should complete after recovery');
  });

  test('failing tests triggers fix then retest (same-agent recovery)', { timeout: 120000 }, async () => {
    const dispatches = [];

    // run_tests fails on first call (claude), then passes on second (after claude fix)
    let testCallCount = 0;
    const overrides = {
      run_tests: () => {
        testCallCount++;
        if (testCallCount === 1) {
          return { passing: false, summary: 'Tests failed', failures: ['test_auth fails', 'test_db timeout'] };
        }
        return { passing: true, summary: 'All tests pass', failures: [] };
      },
    };

    const gateOpts = createAutoApproveGateOpts();

    await runBuild('PROOF-1', {
      cwd: tmpDir,
      connectorFactory: mockConnectorFactory(dispatches, featureDir, overrides),
      description: 'Coverage recovery test',
      gateOpts,
    });

    // The fix prompt contains step "run_tests", so fix and retry both match stepId.
    // All dispatches with stepId === 'run_tests' should be claude (same-agent recovery).
    const testDispatches = dispatches.filter(d => d.stepId.endsWith('/run_tests'));
    assert.ok(testDispatches.length >= 3,
      `Should have at least 3 run_tests dispatches (fail + fix + retest), got ${testDispatches.length}`);

    // All should be claude-family (same-agent recovery)
    for (const d of testDispatches) {
      assert.ok(d.agentType.startsWith('claude'), `run_tests dispatch should be claude-family, got ${d.agentType}`);
    }

    // The sequence should be: run_tests (fail) → fix → run_tests (pass)
    // Fix dispatch should come between the first and last run_tests dispatches
    assert.ok(testDispatches.length >= 3,
      'Should have fix dispatch between fail and retest');

    // Build should complete
    const auditPath = join(tmpDir, 'docs', 'features', 'PROOF-1', 'audit.json');
    assert.ok(existsSync(auditPath), 'audit.json should be written');
    const audit = JSON.parse(readFileSync(auditPath, 'utf-8'));
    assert.equal(audit.status, 'completed', 'build should complete after coverage recovery');
  });
});
