/**
 * proof-run.test.js — Integration test for the full build.stratum.yaml spec.
 *
 * Validates the 12-step lifecycle pipeline with mock connectors and
 * auto-approved gates. Proves the dispatch loop handles skips, gates,
 * sub-flows, artifact file_exists ensures, and cross-agent recovery.
 *
 * Requires stratum-mcp on $PATH — skips if not installed.
 */

import { test, before, after, describe, beforeEach, afterEach } from 'node:test';
import assert from 'node:assert/strict';
import {
  mkdtempSync, mkdirSync, writeFileSync, readFileSync,
  existsSync, rmSync, copyFileSync,
} from 'node:fs';
import { join, resolve, dirname } from 'node:path';
import { tmpdir } from 'node:os';
import { execFileSync } from 'node:child_process';
import { PassThrough } from 'node:stream';

import { runBuild } from '../lib/build.js';

const ROOT = resolve(dirname(import.meta.url.replace('file://', '')));

// ---------------------------------------------------------------------------
// Skip guard
// ---------------------------------------------------------------------------

let stratumAvailable = false;
try {
  execFileSync('stratum-mcp', ['--help'], { timeout: 5000, stdio: 'pipe' });
  stratumAvailable = true;
} catch { /* not installed */ }

// ---------------------------------------------------------------------------
// Mock connector
// ---------------------------------------------------------------------------

/**
 * Creates a connector factory that returns canned results per step.
 * Tracks which steps were dispatched and with which agent type.
 * Creates artifact files that stratum's file_exists ensures check for.
 *
 * @param {Array}  dispatches  - Collects { stepId, agentType, promptSnippet }
 * @param {string} featureDir  - Path to the feature folder for artifact creation
 * @param {object} [overrides] - Per-step result overrides: { stepId: result }
 */
function mockConnectorFactory(dispatches, featureDir, overrides = {}) {
  // Map step IDs to the artifact files their ensure conditions expect.
  // The result.artifact field must match for file_exists(result.artifact) to pass.
  const artifactMap = {
    explore_design: 'design.md',
    blueprint: 'blueprint.md',
    plan: 'plan.md',
  };

  return function factory(agentType, _opts) {
    return {
      async *run(prompt, _runOpts) {
        // Extract step_id from the prompt (format: step "step_id")
        const stepMatch = prompt.match(/step "([^"]+)"/);
        const stepId = stepMatch?.[1] ?? 'unknown';

        dispatches.push({ stepId, agentType, promptSnippet: prompt.slice(0, 120) });

        // Create artifact file if this step produces one
        const artifactFile = artifactMap[stepId];
        if (artifactFile) {
          mkdirSync(featureDir, { recursive: true });
          writeFileSync(
            join(featureDir, artifactFile),
            `# ${stepId}\nGenerated by mock connector.`
          );
        }

        // Check for per-step overrides
        if (overrides[stepId]) {
          const override = typeof overrides[stepId] === 'function'
            ? overrides[stepId](dispatches)
            : overrides[stepId];
          yield { type: 'assistant', content: JSON.stringify(override) };
          yield { type: 'system', subtype: 'complete', agent: 'mock' };
          return;
        }

        // Default contract-matching result
        const result = getStepResult(stepId, featureDir);
        yield { type: 'assistant', content: JSON.stringify(result) };
        yield { type: 'system', subtype: 'complete', agent: 'mock' };
      },
      interrupt() {},
      get isRunning() { return false; },
    };
  };
}

function getStepResult(stepId, featureDir) {
  const artifactMap = {
    explore_design: 'design.md',
    blueprint: 'blueprint.md',
    plan: 'plan.md',
  };
  const artifactFile = artifactMap[stepId];
  // For PhaseResult steps: artifact must be relative path that file_exists can verify
  const artifactPath = artifactFile
    ? `docs/features/${featureDir.split('/').pop()}/${artifactFile}`
    : `${stepId}.md`;

  const phaseResult = {
    phase: stepId,
    artifact: artifactPath,
    outcome: 'complete',
    summary: `${stepId} completed`,
  };
  const reviewResult = { clean: true, summary: 'No issues found', findings: [] };
  const testResult = { passing: true, summary: 'All tests pass', failures: [] };
  const taskGraph = {
    tasks: [
      {
        id: 'task-1',
        description: 'Implement the main feature logic',
        files_owned: ['src/main.js'],
        files_read: ['src/util.js'],
        depends_on: [],
      },
    ],
  };

  switch (stepId) {
    case 'decompose': return taskGraph;
    case 'review': return reviewResult;
    case 'run_tests': return testResult;
    default: return phaseResult;
  }
}

// ---------------------------------------------------------------------------
// Gate auto-approve helper
// ---------------------------------------------------------------------------

function createAutoApproveGateOpts() {
  const output = new PassThrough();
  output.on('data', () => {}); // drain

  return {
    get input() {
      const input = new PassThrough();
      setImmediate(() => {
        input.write('a\n');
        setImmediate(() => { input.write('LGTM\n'); });
      });
      return input;
    },
    output,
  };
}

// ---------------------------------------------------------------------------
// Test setup
// ---------------------------------------------------------------------------

function setupProofProject(tmpDir) {
  const composeDir = join(tmpDir, '.compose');
  mkdirSync(join(composeDir, 'data'), { recursive: true });
  writeFileSync(
    join(composeDir, 'compose.json'),
    JSON.stringify({ version: '1.0', capabilities: { stratum: true } })
  );

  const featureDir = join(tmpDir, 'docs', 'features', 'PROOF-1');
  mkdirSync(featureDir, { recursive: true });
  writeFileSync(join(featureDir, 'design.md'), '# Proof Run\nValidating compose build pipeline.');

  const pipeDir = join(tmpDir, 'pipelines');
  mkdirSync(pipeDir, { recursive: true });
  const realSpec = join(ROOT, '..', 'pipelines', 'build.stratum.yaml');
  copyFileSync(realSpec, join(pipeDir, 'build.stratum.yaml'));

  return { composeDir, featureDir, pipeDir };
}

// ---------------------------------------------------------------------------
// Test: happy path — all steps pass on first try
// ---------------------------------------------------------------------------

describe('proof run: full pipeline', { skip: !stratumAvailable && 'stratum-mcp not installed' }, () => {
  let tmpDir;
  let dispatches;
  let featureDir;

  before(() => {
    tmpDir = mkdtempSync(join(tmpdir(), 'proof-run-'));
    const project = setupProofProject(tmpDir);
    featureDir = project.featureDir;
    dispatches = [];
  });

  after(() => {
    rmSync(tmpDir, { recursive: true, force: true });
  });

  test('16-step pipeline completes with mock connectors', { timeout: 120000 }, async () => {
    const gateOpts = createAutoApproveGateOpts();

    await runBuild('PROOF-1', {
      cwd: tmpDir,
      connectorFactory: mockConnectorFactory(dispatches, featureDir),
      description: 'Proof run integration test',
      gateOpts,
    });

    // --- Verify dispatched steps ---
    const stepIds = dispatches.map(d => d.stepId);

    // These steps should execute (not skipped).
    // v0.3: explore_design, blueprint, verification, plan, decompose are agent-dispatched.
    // execute is parallel_dispatch — its tasks are dispatched individually (not as "execute").
    for (const step of ['explore_design', 'blueprint', 'verification', 'plan', 'decompose']) {
      assert.ok(stepIds.includes(step), `Step "${step}" should have been dispatched`);
    }

    // Skipped steps should NOT appear in dispatches
    for (const step of ['prd', 'architecture', 'report']) {
      assert.ok(!stepIds.includes(step), `Step "${step}" should be skipped, not dispatched`);
    }

    // Sub-flow steps should have dispatched
    assert.ok(stepIds.includes('review'), 'review_check sub-flow: review step should dispatch');
    assert.ok(stepIds.includes('run_tests'), 'coverage_check sub-flow: run_tests step should dispatch');

    // Parallel dispatch tasks should have dispatched (task-1 from mock decompose)
    assert.ok(dispatches.some(d => d.stepId.startsWith('task')),
      'parallel_dispatch should dispatch decomposed tasks');

    // --- Verify cross-agent dispatch ---
    const reviewDispatch = dispatches.find(d => d.stepId === 'review');
    assert.equal(reviewDispatch.agentType, 'codex', 'review step should dispatch to codex agent');

    // Parallel dispatch tasks use the agent from the execute step spec (claude)
    const taskDispatch = dispatches.find(d => d.stepId.startsWith('task'));
    assert.equal(taskDispatch.agentType, 'claude', 'parallel dispatch tasks should dispatch to claude agent');

    // --- Verify audit trail ---
    const auditPath = join(tmpDir, 'docs', 'features', 'PROOF-1', 'audit.json');
    assert.ok(existsSync(auditPath), 'audit.json should be written');
    const audit = JSON.parse(readFileSync(auditPath, 'utf-8'));
    assert.equal(audit.status, 'complete', 'audit status should be complete');
    assert.ok(Array.isArray(audit.trace), 'audit should have trace array');
    assert.ok(audit.total_duration_ms >= 0, 'audit should have total_duration_ms');

    // Trace should include skipped entries
    const skipEntries = audit.trace.filter(t => t.type === 'skip');
    assert.ok(skipEntries.length >= 3,
      `Should have at least 3 skip entries (prd, architecture, report), got ${skipEntries.length}`);

    // Trace should include gate entries
    const gateEntries = audit.trace.filter(t => t.type === 'gate');
    assert.ok(gateEntries.length >= 3,
      `Should have at least 3 gate entries (design, plan, ship), got ${gateEntries.length}`);

    // --- Verify vision state ---
    const visionPath = join(tmpDir, '.compose', 'data', 'vision-state.json');
    assert.ok(existsSync(visionPath), 'vision-state.json should exist');
    const vision = JSON.parse(readFileSync(visionPath, 'utf-8'));
    const item = vision.items.find(i => i.lifecycle?.featureCode === 'PROOF-1');
    assert.ok(item, 'must have feature item');
    assert.equal(item.status, 'complete', 'item status should be complete');

    // Gates should be resolved
    const gates = vision.gates.filter(g => g.itemId === item.id);
    assert.ok(gates.length >= 3, `Should have at least 3 gates, got ${gates.length}`);
    for (const gate of gates) {
      assert.equal(gate.status, 'resolved', `Gate ${gate.id} should be resolved`);
      assert.equal(gate.outcome, 'approve', `Gate ${gate.id} outcome should be 'approve'`);
    }

    // --- Verify terminal state (file retained per STRAT-COMP-4) ---
    const activePath = join(tmpDir, '.compose', 'data', 'active-build.json');
    assert.ok(existsSync(activePath), 'active-build.json should be retained');
    const activeState = JSON.parse(readFileSync(activePath, 'utf-8'));
    assert.equal(activeState.status, 'complete', 'active-build.json should have terminal status "complete"');
    assert.ok(activeState.completedAt, 'active-build.json should have completedAt');
  });
});

// ---------------------------------------------------------------------------
// Test: review failure triggers cross-agent recovery
// ---------------------------------------------------------------------------

describe('proof run: cross-agent recovery', { skip: !stratumAvailable && 'stratum-mcp not installed' }, () => {
  let tmpDir;
  let featureDir;

  beforeEach(() => {
    tmpDir = mkdtempSync(join(tmpdir(), 'proof-recovery-'));
    const project = setupProofProject(tmpDir);
    featureDir = project.featureDir;
  });

  afterEach(() => {
    rmSync(tmpDir, { recursive: true, force: true });
  });

  test('failing review triggers claude fix then codex re-review', { timeout: 120000 }, async () => {
    const dispatches = [];

    // Review fails on first call (codex), then passes on second (after claude fix)
    let reviewCallCount = 0;
    const overrides = {
      review: () => {
        reviewCallCount++;
        if (reviewCallCount === 1) {
          return { clean: false, summary: 'Found issues', findings: ['unused import', 'missing test'] };
        }
        return { clean: true, summary: 'All clean', findings: [] };
      },
    };

    const gateOpts = createAutoApproveGateOpts();

    await runBuild('PROOF-1', {
      cwd: tmpDir,
      connectorFactory: mockConnectorFactory(dispatches, featureDir, overrides),
      description: 'Recovery test',
      gateOpts,
    });

    // Should see: codex review (fail) → claude fix → codex review (pass)
    // Note: the fix prompt also contains step "review", so all three dispatches
    // have stepId === 'review'. Distinguish by agentType.
    const reviewDispatches = dispatches.filter(d => d.stepId === 'review');
    assert.ok(reviewDispatches.length >= 3,
      `Should have at least 3 review dispatches (codex fail + claude fix + codex pass), got ${reviewDispatches.length}`);

    // First dispatch should be codex (the failing review)
    assert.equal(reviewDispatches[0].agentType, 'codex', '1st review dispatch should be codex');

    // There should be a claude fix dispatch (cross-agent recovery)
    const claudeFix = reviewDispatches.find(d => d.agentType === 'claude');
    assert.ok(claudeFix, 'Should have a claude fix dispatch (cross-agent recovery)');

    // The claude fix should come after the first codex review
    const firstCodexIdx = dispatches.indexOf(reviewDispatches[0]);
    const claudeFixIdx = dispatches.indexOf(claudeFix);
    assert.ok(claudeFixIdx > firstCodexIdx, 'Claude fix should come after first codex review');

    // There should be a second codex review after the claude fix
    const codexAfterFix = reviewDispatches.find(
      d => d.agentType === 'codex' && dispatches.indexOf(d) > claudeFixIdx
    );
    assert.ok(codexAfterFix, 'Should have a codex re-review after claude fix');

    // Build should complete successfully
    const auditPath = join(tmpDir, 'docs', 'features', 'PROOF-1', 'audit.json');
    assert.ok(existsSync(auditPath), 'audit.json should be written');
    const audit = JSON.parse(readFileSync(auditPath, 'utf-8'));
    assert.equal(audit.status, 'complete', 'build should complete after recovery');
  });

  test('failing tests triggers fix then retest (same-agent recovery)', { timeout: 120000 }, async () => {
    const dispatches = [];

    // run_tests fails on first call (claude), then passes on second (after claude fix)
    let testCallCount = 0;
    const overrides = {
      run_tests: () => {
        testCallCount++;
        if (testCallCount === 1) {
          return { passing: false, summary: 'Tests failed', failures: ['test_auth fails', 'test_db timeout'] };
        }
        return { passing: true, summary: 'All tests pass', failures: [] };
      },
    };

    const gateOpts = createAutoApproveGateOpts();

    await runBuild('PROOF-1', {
      cwd: tmpDir,
      connectorFactory: mockConnectorFactory(dispatches, featureDir, overrides),
      description: 'Coverage recovery test',
      gateOpts,
    });

    // The fix prompt contains step "run_tests", so fix and retry both match stepId.
    // All dispatches with stepId === 'run_tests' should be claude (same-agent recovery).
    const testDispatches = dispatches.filter(d => d.stepId === 'run_tests');
    assert.ok(testDispatches.length >= 3,
      `Should have at least 3 run_tests dispatches (fail + fix + retest), got ${testDispatches.length}`);

    // All should be claude (same-agent)
    for (const d of testDispatches) {
      assert.equal(d.agentType, 'claude', `run_tests dispatch should be claude, got ${d.agentType}`);
    }

    // The sequence should be: run_tests (fail) → fix → run_tests (pass)
    // Fix dispatch should come between the first and last run_tests dispatches
    assert.ok(testDispatches.length >= 3,
      'Should have fix dispatch between fail and retest');

    // Build should complete
    const auditPath = join(tmpDir, 'docs', 'features', 'PROOF-1', 'audit.json');
    assert.ok(existsSync(auditPath), 'audit.json should be written');
    const audit = JSON.parse(readFileSync(auditPath, 'utf-8'));
    assert.equal(audit.status, 'complete', 'build should complete after coverage recovery');
  });
});
